apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  destinations:
    - name: "*"
      namespace: kargo-helm*
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://github.com/robinlioret/kargo-helm.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-helm
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/robinlioret/kargo-helm.git
        revision: HEAD
        directories:
          - path: env/*
  template:
    metadata:
      name: kargo-helm-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-helm:{{path.basename}}
    spec:
      destination:
        namespace: kargo-helm-{{path.basename}}
        server: https://kubernetes.default.svc
      project: kargo-helm
      source:
        path: charts/guestbook
        repoURL: https://github.com/robinlioret/kargo-helm.git
        helm:
          valueFiles:
            - "/env/{{path.basename}}/values.yaml"
            - "/env/{{path.basename}}/feature-flags.yaml"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
