---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-helm
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-helm
  namespace: kargo-helm
  annotations:
    # This annotation ensures Projects (Namespaces) are created first when deployed via Argo CD
    argocd.argoproj.io/sync-wave: "-1"
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
    - stageSelector:
        name: staging
      autoPromotionEnabled: true
    - stageSelector:
        matchLabels:
          environment: prod
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: kargo-helm
spec:
  vars:
    - name: image
      value: registry.sandbox.local/guestbook
    - name: repoURL
      value: https://github.com/robinlioret/kargo-helm.git
    - name: branch
      value: main
    - name: envPath
    - name: argocdApp

  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.repoURL }}
        checkout:
          - commit: ${{ commitFrom( vars.repoURL ).ID }}
            path: ./src
          - branch: ${{ vars.branch }}
            path: ./out
    - uses: yaml-update
      as: update-image
      config:
        path: ./out/${{ vars.envPath }}/values.yaml
        updates:
          - key: image.tag
            value: ${{ imageFrom( vars.image ).Tag }}
    - uses: copy
      config:
        inPath: ./src/base/feature-flags.yaml
        outPath: ./out/${{ vars.envPath }}/feature-flags.yaml
    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: ${{ task.outputs['update-image'].commitMessage }}
    - uses: git-push
      config:
        path: ./out
    - uses: argocd-update
      config:
        apps:
          - name: ${{ vars.argocdApp }}
