apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: dev-roblio-guestbook
  namespace: kargo-helm
spec:
  subscriptions:
    - git:
        branch: roblio
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
        repoURL: https://github.com/robinlioret/kargo-helm.git
        includePaths:
          - base/feature-flags.yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev-roblio-guestbook
  namespace: kargo-helm
  labels:
    environment: prod
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: true
        # stages:
        #   - prod-ready
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-dev-roblio-guestbook
