
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-1
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-2
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-3
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-4
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-5
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-6
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-7
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-8
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-9
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-10
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-11
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-12
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-13
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-14
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-15
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-16
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-17
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-18
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-19
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-20
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-21
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-22
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-23
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-24
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-25
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-26
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-27
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-28
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-29
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-30
  namespace: kargo-helm
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/prod
            - name: argocdApp
              value: kargo-helm-prod
---
