{{- if .Values.kargoStage.enabled }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .Values.kargoStage.name }}
  namespace: {{ .Values.kargoStage.projectName }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        {{- with .Values.kargoStage.previousStages }}
        stages: {{ . }}
        {{- end }}
        {{- with .Values.kargoStage.direct }}
        direct: {{ . }}
        {{- end }}
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/{{ .Values.kargoStage.name }}
            - name: argocdApp
              value: kargo-helm-{{ .Values.kargoStage.name }}
{{- end }}