{{- if .Values.kargoStage.enabled }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ .Values.kargoStage.name }}
  namespace: {{ .Values.kargoStage.projectName }}
spec:
  subscriptions:
    - git:
        branch: {{ .Values.kargoStage.branchName }}
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
        repoURL: https://github.com/robinlioret/kargo-helm.git
        includePaths:
          - base/feature-flags.yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .Values.kargoStage.name }}
  namespace: {{ .Values.kargoStage.projectName }}
  annotations:
    kargo.akuity.io/color: {{ .Values.kargoStage.color | default "green" }}
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        {{- with .Values.kargoStage.previousStages }}
        stages: {{ . }}
        {{- end }}
        {{- with .Values.kargoStage.direct }}
        direct: {{ . }}
        {{- end }}
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote
          vars:
            - name: envPath
              value: env/{{ .Values.kargoStage.name }}
            - name: argocdApp
              value: kargo-helm-{{ .Values.kargoStage.name }}
{{- end }}